name: audio_youtube
description: "A new Flutter project."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# widgets
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  sliding_up_panel: ^2.0.0+1
  curved_navigation_bar: ^1.0.6
  skeletonizer: ^1.4.2
  flutter_speed_dial: ^7.0.0
  audio_video_progress_bar: ^2.0.3
  fluentui_system_icons: ^1.1.257
  modal_bottom_sheet: ^3.0.0

# debug
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0

# controller 
  get: ^4.6.6
  go_router: ^14.2.7

# firebase
  firebase_core: ^3.3.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.4
  firebase_messaging: ^15.1.0
  
# model
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1

# network
  flutter_inappwebview: ^6.1.5
  dio: ^5.6.0

# audio
  just_audio: ^0.9.37
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  flutter_tts: ^3.8.5	
  flowery_tts:
    git:
      url: https://github.com/boomtn2/flowery_api_tts.git
      ref: fix_model

 # other
  rxdart: ^0.27.7
  youtube_explode_dart: ^2.3.1
  dart_rss: ^3.0.3
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  flutter_spinkit: ^5.2.1
  disable_battery_optimization: ^1.1.1
  rive: ^0.13.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: 5.7.0
  flutter_localizations:
    sdk: flutter

 
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    rive: true
    lottie: true


flutter:
 
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
    - assets/rives/
  fonts:
    - family: Afacad
      fonts:
        - asset: assets/fonts/afacad/Afacad-Regular.ttf
          weight: 200
        - asset: assets/fonts/afacad/Afacad-Medium.ttf
          weight: 300
        - asset: assets/fonts/afacad/Afacad-MediumItalic.ttf
          weight: 300
          style: italic  
        - asset: assets/fonts/afacad/Afacad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/afacad/Afacad-SemiBoldItalic.ttf
          weight: 600
          style: italic 
        - asset: assets/fonts/afacad/Afacad-Bold.ttf
          weight: 700
        - asset: assets/fonts/afacad/Afacad-BoldItalic.ttf
          weight: 700
          style: italic  
        - asset: assets/fonts/afacad/Afacad-Italic.ttf
          style: italic  
   