// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxlvRhvDO_-xDL-vn6Rsk_PB9Kh09Cxk',
    appId: '1:817390492252:android:dbdec40d9c0fd8582f2499',
    messagingSenderId: '817390492252',
    projectId: 'audio-quan-hon-ngon-tinh',
    storageBucket: 'audio-quan-hon-ngon-tinh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0UJLKoheuMVoT-rYMZwG_6MwDwLMYwBM',
    appId: '1:817390492252:ios:23aff5ccd84f94d52f2499',
    messagingSenderId: '817390492252',
    projectId: 'audio-quan-hon-ngon-tinh',
    storageBucket: 'audio-quan-hon-ngon-tinh.appspot.com',
    iosClientId:
        '817390492252-malrciksn2vkkn1o5t4dh9d38i2bdae6.apps.googleusercontent.com',
    iosBundleId: 'hit.coder.ttsaudioquanhonngontinh',
  );
}
